from django.urls import path
from .views import (
    PerfilAcademicoView, 
    MateriaDetalheView,
    UploadHorarioView, 
    ControleFaltaView, 
    ConfiguracaoMateriaView, 
    AvaliacaoView,
    AnotacaoMateriaView,
    ConfiguracaoClassroomView,
    ListarCursosClassroomView,
    VincularCursoClassroomView,
    ArquivosMateriaClassroomView,
    AtualizarCategoriasVinculoView,
    AtualizarArquivoClassroomView,
    BaixarArquivoClassroomView,
    ExploradorDiretoriosView,
    AbrirArquivoLocalView,
    AdicionarArquivoLocalView,
    ObterConteudoArquivoDriveView,
    SincronizarArquivosLocaisView,
    MuralClassroomView,
    MarcarMuralLidoView,
    NotificacoesClassroomView,
    ObterInfoAgendaView,
    RegenerarTokenAgendaView,
    FeedAgendaView,
    ListarCriarChamadoView,
    DetalheChamadoSuporteView,
    AtualizarStatusChamadoView,
    VisualizarEstatisticasAdminView,
    ListarUsuariosAdminView,
    AlternarAcessoAdminView,
    ListarCriarNoticiaView,
    DetalheNoticiaView,
    ConfiguracaoIAView,
    ChatIAView,
    ConversasIAView,
    ConversaIADetalheView,
    EnviarMensagemConversaView
)

urlpatterns = [
    path('perfil/', PerfilAcademicoView.as_view(), name='perfil'),
    path('materias/<int:materia_id>/', MateriaDetalheView.as_view(), name='materia_detalhe'),
    path('upload-horario/', UploadHorarioView.as_view(), name='upload_horario'),
    path('controle-falta/', ControleFaltaView.as_view(), name='controle_falta'),
    path('configuracao-notas/', ConfiguracaoMateriaView.as_view(), name='configuracao_notas'),
    path('avaliacoes/', AvaliacaoView.as_view(), name='avaliacoes'),
    path('avaliacoes/<int:pk>/', AvaliacaoView.as_view(), name='avaliacao_detalhe'),
    path('anotacoes/', AnotacaoMateriaView.as_view(), name='anotacoes'),
    path('anotacoes/<int:pk>/', AnotacaoMateriaView.as_view(), name='anotacao_detalhe'),
    path('classroom/config/', ConfiguracaoClassroomView.as_view(), name='classroom_config'),
    path('classroom/cursos/', ListarCursosClassroomView.as_view(), name='classroom_cursos'),
    path('classroom/vincular/', VincularCursoClassroomView.as_view(), name='classroom_vincular'),
    path('classroom/vincular/categorias/', AtualizarCategoriasVinculoView.as_view(), name='classroom_vincular_categorias'),
    path('classroom/arquivos/', ArquivosMateriaClassroomView.as_view(), name='classroom_arquivos'),
    path('classroom/arquivos/abrir/', AbrirArquivoLocalView.as_view(), name='classroom_abrir_arquivo'),
    path('classroom/arquivos/upload-local/', AdicionarArquivoLocalView.as_view(), name='classroom_upload_local'),
    path('classroom/arquivos/sincronizar/', SincronizarArquivosLocaisView.as_view(), name='classroom_sincronizar_arquivos'),
    path('classroom/arquivos/<str:drive_file_id>/', AtualizarArquivoClassroomView.as_view(), name='classroom_arquivos_detalhe'),
    path('classroom/arquivos/<str:drive_file_id>/conteudo/', ObterConteudoArquivoDriveView.as_view(), name='classroom_arquivos_conteudo'),
    path('classroom/arquivos/<str:drive_file_id>/baixar/', BaixarArquivoClassroomView.as_view(), name='classroom_arquivos_baixar'),
    path('classroom/explorar-diretorios/', ExploradorDiretoriosView.as_view(), name='classroom_explorar_diretorios'),
    path('classroom/mural/', MuralClassroomView.as_view(), name='classroom_mural'),
    path('classroom/mural/marcar-lido/', MarcarMuralLidoView.as_view(), name='classroom_mural_marcar_lido'),
    path('classroom/notificacoes/', NotificacoesClassroomView.as_view(), name='classroom_notificacoes'),
    path('agenda/info/', ObterInfoAgendaView.as_view(), name='agenda_info'),
    path('agenda/regenerar/', RegenerarTokenAgendaView.as_view(), name='agenda_regenerar'),
    path('agenda/feed/<uuid:token>/', FeedAgendaView.as_view(), name='agenda_feed'),
    path('suporte/chamados/', ListarCriarChamadoView.as_view(), name='listar_criar_chamado'),
    path('suporte/chamados/<int:pk>/', DetalheChamadoSuporteView.as_view(), name='detalhe_chamado_suporte'),
    path('suporte/chamados/<int:pk>/status/', AtualizarStatusChamadoView.as_view(), name='atualizar_status_chamado'),
    path('admin/estatisticas/', VisualizarEstatisticasAdminView.as_view(), name='visualizar_estatisticas_admin'),
    path('admin/usuarios/', ListarUsuariosAdminView.as_view(), name='listar_usuarios_admin'),
    path('admin/usuarios/<int:pk>/alternar-staff/', AlternarAcessoAdminView.as_view(), name='alternar_acesso_admin'),
    path('noticias/', ListarCriarNoticiaView.as_view(), name='listar_criar_noticia'),
    path('noticias/<int:pk>/', DetalheNoticiaView.as_view(), name='detalhe_noticia'),
    path('ia/config/', ConfiguracaoIAView.as_view(), name='ia_config'),
    path('ia/chat/', ChatIAView.as_view(), name='ia_chat'),
    path('ia/conversas/', ConversasIAView.as_view(), name='ia_conversas'),
    path('ia/conversas/<int:pk>/', ConversaIADetalheView.as_view(), name='ia_conversa_detalhe'),
    path('ia/conversas/<int:pk>/enviar/', EnviarMensagemConversaView.as_view(), name='ia_conversa_enviar'),
]


