from django.urls import path
from .views import (
    PerfilAcademicoView, 
    UploadHorarioView, 
    ControleFaltaView, 
    ConfiguracaoMateriaView, 
    AvaliacaoView,
    ConfiguracaoClassroomView,
    ListarCursosClassroomView,
    VincularCursoClassroomView,
    ArquivosMateriaClassroomView,
    AtualizarArquivoClassroomView,
    BaixarArquivoClassroomView,
    ExploradorDiretoriosView,
    AbrirArquivoLocalView,
    AdicionarArquivoLocalView,
    ObterConteudoArquivoDriveView,
    SincronizarArquivosLocaisView,
    MuralClassroomView,
    MarcarMuralLidoView,
    NotificacoesClassroomView,
    ObterInfoAgendaView,
    RegenerarTokenAgendaView,
    FeedAgendaView
)

urlpatterns = [
    path('perfil/', PerfilAcademicoView.as_view(), name='perfil'),
    path('upload-horario/', UploadHorarioView.as_view(), name='upload_horario'),
    path('controle-falta/', ControleFaltaView.as_view(), name='controle_falta'),
    path('configuracao-notas/', ConfiguracaoMateriaView.as_view(), name='configuracao_notas'),
    path('avaliacoes/', AvaliacaoView.as_view(), name='avaliacoes'),
    path('avaliacoes/<int:pk>/', AvaliacaoView.as_view(), name='avaliacao_detalhe'),
    path('classroom/config/', ConfiguracaoClassroomView.as_view(), name='classroom_config'),
    path('classroom/cursos/', ListarCursosClassroomView.as_view(), name='classroom_cursos'),
    path('classroom/vincular/', VincularCursoClassroomView.as_view(), name='classroom_vincular'),
    path('classroom/arquivos/', ArquivosMateriaClassroomView.as_view(), name='classroom_arquivos'),
    path('classroom/arquivos/abrir/', AbrirArquivoLocalView.as_view(), name='classroom_abrir_arquivo'),
    path('classroom/arquivos/upload-local/', AdicionarArquivoLocalView.as_view(), name='classroom_upload_local'),
    path('classroom/arquivos/sincronizar/', SincronizarArquivosLocaisView.as_view(), name='classroom_sincronizar_arquivos'),
    path('classroom/arquivos/<str:drive_file_id>/', AtualizarArquivoClassroomView.as_view(), name='classroom_arquivos_detalhe'),
    path('classroom/arquivos/<str:drive_file_id>/conteudo/', ObterConteudoArquivoDriveView.as_view(), name='classroom_arquivos_conteudo'),
    path('classroom/arquivos/<str:drive_file_id>/baixar/', BaixarArquivoClassroomView.as_view(), name='classroom_arquivos_baixar'),
    path('classroom/explorar-diretorios/', ExploradorDiretoriosView.as_view(), name='classroom_explorar_diretorios'),
    path('classroom/mural/', MuralClassroomView.as_view(), name='classroom_mural'),
    path('classroom/mural/marcar-lido/', MarcarMuralLidoView.as_view(), name='classroom_mural_marcar_lido'),
    path('classroom/notificacoes/', NotificacoesClassroomView.as_view(), name='classroom_notificacoes'),
    path('agenda/info/', ObterInfoAgendaView.as_view(), name='agenda_info'),
    path('agenda/regenerar/', RegenerarTokenAgendaView.as_view(), name='agenda_regenerar'),
    path('agenda/feed/<uuid:token>/', FeedAgendaView.as_view(), name='agenda_feed'),
]


