# Generated by Django 6.0.5 on 2026-05-19 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('turma', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('maximo_faltas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.IntegerField()),
                ('aula', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('sala', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='a_academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_academico.curso')),
                ('materias', models.ManyToManyField(blank=True, to='a_academico.materia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_academico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
