# Generated by Django 6.0.5 on 2026-05-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.IntegerField(default=0)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_academico.materia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_falta', to='a_academico.perfilacademico')),
            ],
            options={
                'unique_together': {('perfil', 'materia')},
            },
        ),
    ]
