# Generated by Django 6.0.5 on 2026-05-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('horarios', models.ManyToManyField(blank=True, to='a_academico.horario')),
                ('materias', models.ManyToManyField(blank=True, to='a_academico.materia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos', to='a_academico.perfilacademico')),
            ],
            options={
                'unique_together': {('perfil', 'ano')},
            },
        ),
        migrations.AddField(
            model_name='registrofalta',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_falta', to='a_academico.anoletivo'),
        ),
    ]
