# Generated by Django 6.0.5 on 2026-05-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0002_controlefalta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('faltas', models.IntegerField(default=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_academico.materia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_falta', to='a_academico.perfilacademico')),
            ],
            options={
                'unique_together': {('perfil', 'materia', 'data')},
            },
        ),
        migrations.DeleteModel(
            name='ControleFalta',
        ),
    ]
