# Generated by Django 6.0.5 on 2026-05-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0002_anoletivo_registrofalta_ano_letivo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('materia', 'turma', 'aula', 'dia')},
        ),
    ]
