# Generated by Django 6.0.5 on 2026-05-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0003_alter_horario_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_minima', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_materias', to='a_academico.anoletivo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_academico.materia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_materias', to='a_academico.perfilacademico')),
            ],
            options={
                'unique_together': {('perfil', 'materia', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('EXAME', 'Exame'), ('OUTRO', 'Outro')], default='PROVA', max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='a_academico.configuracaomateria')),
            ],
        ),
    ]
