# Generated by Django 6.0.5 on 2026-05-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0003_registrofalta_delete_controlefalta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrofalta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registrofalta',
            name='aula',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='registrofalta',
            unique_together={('perfil', 'materia', 'data', 'aula')},
        ),
    ]
