# Generated by Django 6.0.5 on 2026-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0004_configuracaomateria_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
