# Generated by Django 6.0.5 on 2026-05-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0005_alter_avaliacao_options_avaliacao_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeralClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_dir', models.CharField(default='Downloads/MinhaUEM', max_length=500)),
                ('folder_options', models.CharField(default='docs,exercicios', max_length=500)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_classroom', to='a_academico.perfilacademico')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoGoogleClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_course_id', models.CharField(max_length=100)),
                ('classroom_course_name', models.CharField(max_length=255)),
                ('subject_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_classroom', to='a_academico.configuracaomateria')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoMateriaClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=100, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_folder', models.CharField(default='docs', max_length=100)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('sync_at', models.DateTimeField(auto_now=True)),
                ('classroom_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='a_academico.vinculogoogleclassroom')),
            ],
        ),
    ]
