# Generated by Django 6.0.5 on 2026-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0006_configuracaogeralclassroom_vinculogoogleclassroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivomateriaclassroom',
            name='is_downloaded',
        ),
        migrations.AddField(
            model_name='arquivomateriaclassroom',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arquivomateriaclassroom',
            name='selected_folder',
            field=models.CharField(default='documentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaogeralclassroom',
            name='folder_options',
            field=models.CharField(default='documentos,exercicios', max_length=500),
        ),
    ]
