# Generated by Django 6.0.5 on 2026-05-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0007_remove_arquivomateriaclassroom_is_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivomateriaclassroom',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
