# Generated by Django 6.0.5 on 2026-05-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0008_arquivomateriaclassroom_is_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivomateriaclassroom',
            name='is_downloaded',
        ),
    ]
