# Generated by Django 6.0.5 on 2026-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0010_converter_docs_para_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculogoogleclassroom',
            name='ultimo_acesso_mural',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
