# Generated by Django 6.0.5 on 2026-05-22 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0011_vinculogoogleclassroom_ultimo_acesso_mural'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacademico',
            name='calendar_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
