# Generated by Django 6.0.5 on 2026-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0012_perfilacademico_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('EXAME', 'Exame'), ('TAREFA', 'Tarefa'), ('PESQUISA', 'Pesquisa'), ('OUTRO', 'Outro')], default='PROVA', max_length=20),
        ),
    ]
