# Generated by Django 6.0.5 on 2026-05-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0013_alter_avaliacao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subject_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='a_academico.configuracaomateria')),
            ],
        ),
    ]
