# Generated by Django 6.0.5 on 2026-05-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0016_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='category',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('ACADEMICO', 'Acadêmico'), ('CLASSROOM', 'Google Classroom'), ('MANUTENCAO', 'Manutenção'), ('NOVIDADES', 'Novidades')], default='GERAL', max_length=20),
        ),
    ]
