# Generated by Django 6.0.5 on 2026-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0017_alter_noticia_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculogoogleclassroom',
            name='custom_folders',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
