# Generated by Django 6.0.5 on 2026-06-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0018_vinculogoogleclassroom_custom_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculogoogleclassroom',
            name='classroom_alternate_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ProfessorClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('classroom_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='a_academico.vinculogoogleclassroom')),
            ],
        ),
    ]
