# Generated by Django 6.0.5 on 2026-06-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0019_vinculogoogleclassroom_classroom_alternate_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveApiGemini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chave_gemini', to='a_academico.perfilacademico')),
            ],
        ),
    ]
