# Generated by Django 6.0.5 on 2026-06-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0020_chaveapigemini'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaveapigemini',
            name='model_name',
            field=models.CharField(default='gemini-3.5-flash', max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricoUsoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField()),
                ('candidate_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ia', to='a_academico.perfilacademico')),
            ],
        ),
    ]
