# Generated by Django 6.0.5 on 2026-06-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0021_chaveapigemini_model_name_historicousoia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_ia', to='a_academico.materia')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ia', to='a_academico.perfilacademico')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemConversaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('conversa', 'Conversa'), ('user', 'User'), ('model', 'Model')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a_academico.conversaia')),
            ],
        ),
    ]
