# Generated by Django 6.0.5 on 2026-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0022_conversaia_mensagemconversaia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivomateriaclassroom',
            name='drive_file_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='arquivomateriaclassroom',
            unique_together={('classroom_connection', 'drive_file_id')},
        ),
    ]
