# Generated by Django 6.0.5 on 2026-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0023_alter_arquivomateriaclassroom_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='A_FAZER', max_length=20),
        ),
    ]
