# Generated by Django 6.0.5 on 2026-06-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_academico', '0024_avaliacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMateriaClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('drive', 'Google Drive'), ('youtube', 'YouTube')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_folder', models.CharField(default='videos', max_length=100)),
                ('is_ignored', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('sync_at', models.DateTimeField(auto_now=True)),
                ('classroom_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='a_academico.vinculogoogleclassroom')),
            ],
            options={
                'unique_together': {('classroom_connection', 'video_id')},
            },
        ),
    ]
